#include "Element.h"
#include "UIElement.h"
#include "GameElement.h"

#include <vector>

#ifndef SESSION_H
#define SESSION_H


namespace gameEngine
{

  class Session
  {

  public:
    // Default-konstruktor
    Session();
    void addUIElement(std::shared_ptr<UIElement>);
    void addGameElement(std::shared_ptr<GameElement>);
    void removeUIElement(std::shared_ptr<UIElement>);
    void removeGameElement(std::shared_ptr<GameElement>);
    void removeAllElements();
    const int noOfGameElements() const {
	  return allGameElements
    .size();
    }
    void setScore(int sc) {
      score = sc;
    }

    int getScore() {
      return score;
    }


    void run();
    // Destruktor
    ~Session(){};

  private:
    
    void checkUserInput();
    void autogenerateObject();
    void addTarget();
    void updateObjectsState();
    void checkForCollision();
    void handleAddedObjects();
    void handleRemovedObjects();
    void drawObjects();
    void handleDelay();
    
    Uint32 nextTick;
    bool quit = false;
    int score = 0;
    int tickCount = 0;

    /*All*/
    // Samling av alla objekt
    std::vector<std::shared_ptr<Element>> allElements;

    // Samling av alla UI-objekt
    std::vector<std::shared_ptr<UIElement>> allUIElements;

    // Samling av alla Game-objekt
    std::vector<std::shared_ptr<GameElement>> allGameElements;

    /*All added*/
    // Samling av alla adderade objekt
    std::vector<std::shared_ptr<Element>> allElementsAdded;

    // Samling av alla adderade UI-objekt
    std::vector<std::shared_ptr<UIElement>> allUIElementsAdded;

    // Samling av alla adderade Game-objekt
    std::vector<std::shared_ptr<GameElement>> allGameElementsAdded;

    /*All deleted*/
    // Samling av alla raderade objekt
    std::vector<std::shared_ptr<Element>> allElementsRemoved;

    // Samling av alla raderade UI-objekt
    std::vector<std::shared_ptr<UIElement>> allUIElementsRemoved;

    // Samling av alla raderade Game-objekt
    std::vector<std::shared_ptr<GameElement>> allGameElementsRemoved;

    std::vector<std::shared_ptr<GameElement>> autogeneratedGameElements;


  };
}

#endif