#include "Element.h"
#include "UIElement.h"
#include "GameElement.h"

#include <vector>

#ifndef SESSION_H
#define SESSION_H

namespace gameEngine
{

  class Session
  {

  public:
    // Default-konstruktor
    Session();
    void addElement(std::shared_ptr<Element>);
    void removeElement(std::shared_ptr<Element>);
    void removeAllElements();

    void setScore(int sc)
    {
      score = sc;
    }

    int getScore()
    {
      return score;
    }

    void run();
    // Destruktor
    ~Session(){};

  private:
    void checkUserInput();
    void autogenerateObject();
    void checkObjectsState();
    void updateObjectsState();
    void checkForCollision();
    void handleAddedObjects();
    void handleRemovedObjects();
    void drawObjects();
    void handleDelay();

    Uint32 nextTick;
    bool quit = false;
    int score = 0;
    int tickCount = 0;

    /*All*/
    // Samling av alla objekt
    std::vector<std::shared_ptr<Element>> allElements;

    /*All added*/
    // Samling av alla adderade objekt
    std::vector<std::shared_ptr<Element>> allElementsAdded;

    /*All deleted*/
    // Samling av alla raderade objekt
    std::vector<std::shared_ptr<Element>> allElementsRemoved;

    /*All objects to autogenerate*/
    std::vector<std::shared_ptr<Element>> autogeneratedElements;
  };
}

#endif